version: "3.7"

services:
  local_mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: demo_testing
    ports:
      - 27017:27017
    volumes:
      - ./db_data:/data/db